apiVersion: v1
kind: Service
metadata:
  name: webrobot-etl-api-doc-service
  namespace: webrobot-api
  labels:
    app: webrobot-etl-api-doc
    service: api-doc
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: webrobot-etl-api-doc
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

